// <auto-generated />
using System;
using BnGClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BnGClub.Data.BNGMigrations
{
    [DbContext(typeof(BnGClubContext))]
    partial class BnGClubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BNG")
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BnGClub.Models.Activities", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActTypeID");

                    b.Property<int>("LeaderID");

                    b.Property<string>("actAvailablePlace")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("actCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("actDescription")
                        .IsRequired();

                    b.Property<string>("actName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("actRequirement")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("ActTypeID");

                    b.HasIndex("LeaderID");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("BnGClub.Models.ActType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("acttypeDescription")
                        .IsRequired();

                    b.Property<string>("acttypeName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("ActTypes");
                });

            modelBuilder.Entity("BnGClub.Models.Announcement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActID");

                    b.Property<int>("LeaderID");

                    b.Property<DateTime?>("annDate")
                        .IsRequired();

                    b.Property<string>("annMessage")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("ActID");

                    b.HasIndex("LeaderID");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("BnGClub.Models.Child", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserID");

                    b.Property<DateTime?>("childDOB")
                        .IsRequired();

                    b.Property<string>("childFName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("childLName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("childMName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Childs");
                });

            modelBuilder.Entity("BnGClub.Models.childEnrolled", b =>
                {
                    b.Property<int>("ActID");

                    b.Property<int>("ChildID");

                    b.Property<int>("ID");

                    b.HasKey("ActID", "ChildID");

                    b.HasIndex("ChildID");

                    b.ToTable("childEnrolleds");
                });

            modelBuilder.Entity("BnGClub.Models.Leader", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("leaderEmail")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("leaderFName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("leaderLName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("leaderMName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("leaderPhone");

                    b.HasKey("ID");

                    b.HasIndex("leaderEmail")
                        .IsUnique();

                    b.ToTable("Leaders");
                });

            modelBuilder.Entity("BnGClub.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("msgBody")
                        .IsRequired();

                    b.Property<string>("msgFrom")
                        .IsRequired();

                    b.Property<string>("msgTo")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BnGClub.Models.Schedules", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActID");

                    b.Property<DateTime>("dateAct");

                    b.Property<DateTime>("endTime");

                    b.Property<DateTime>("startTime");

                    b.HasKey("ID");

                    b.HasIndex("ActID");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("BnGClub.Models.Subscriptions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChildID");

                    b.Property<int?>("LeaderID");

                    b.Property<string>("Name")
                        .HasMaxLength(127);

                    b.Property<string>("PushAuth")
                        .HasMaxLength(512);

                    b.Property<string>("PushEndpoint")
                        .HasMaxLength(512);

                    b.Property<string>("PushP256DH")
                        .HasMaxLength(512);

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("ChildID");

                    b.HasIndex("LeaderID");

                    b.HasIndex("UserID");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("BnGClub.Models.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("notificationOptIn");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("userFName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("userLName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("userMName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("userPhone");

                    b.HasKey("ID");

                    b.HasIndex("userEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BnGClub.Models.Activities", b =>
                {
                    b.HasOne("BnGClub.Models.ActType", "ActType")
                        .WithMany("Activities")
                        .HasForeignKey("ActTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BnGClub.Models.Leader", "Leader")
                        .WithMany("Activities")
                        .HasForeignKey("LeaderID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BnGClub.Models.Announcement", b =>
                {
                    b.HasOne("BnGClub.Models.Activities", "Activities")
                        .WithMany("Announcements")
                        .HasForeignKey("ActID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BnGClub.Models.Leader", "Leader")
                        .WithMany("Announcements")
                        .HasForeignKey("LeaderID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BnGClub.Models.Child", b =>
                {
                    b.HasOne("BnGClub.Models.Users", "User")
                        .WithMany("Children")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BnGClub.Models.childEnrolled", b =>
                {
                    b.HasOne("BnGClub.Models.Activities", "Activities")
                        .WithMany("ChildEnrolleds")
                        .HasForeignKey("ActID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BnGClub.Models.Child", "Child")
                        .WithMany("ChildEnrolleds")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BnGClub.Models.Schedules", b =>
                {
                    b.HasOne("BnGClub.Models.Activities", "Activities")
                        .WithMany("Schedules")
                        .HasForeignKey("ActID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BnGClub.Models.Subscriptions", b =>
                {
                    b.HasOne("BnGClub.Models.Child")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ChildID");

                    b.HasOne("BnGClub.Models.Leader")
                        .WithMany("Subscriptions")
                        .HasForeignKey("LeaderID");

                    b.HasOne("BnGClub.Models.Users", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
